-- clear tables for fresh start
DROP TABLE IF EXISTS MERCHANDISE;
DROP TABLE IF EXISTS TICKET;
DROP TABLE IF EXISTS CONCERT;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS ARTIST;

-- create tables
CREATE TABLE ARTIST (
    ARTIST_ID       INT             AUTO_INCREMENT      PRIMARY KEY,
    ARTIST_NAME     VARCHAR(20)     NOT NULL,
    GENRE           VARCHAR(20)
);
CREATE TABLE CUSTOMER (
    CUSTOMER_ID     INT             AUTO_INCREMENT      PRIMARY KEY,
    CUSTOMER_NAME   VARCHAR(20)     NOT NULL
);
CREATE TABLE CONCERT(
    CONCERT_ID      INT             AUTO_INCREMENT      PRIMARY KEY,
    VENUE_NAME      VARCHAR(30)     NOT NULL,
    CITY            VARCHAR(20)     NOT NULL,
    CONCERT_DATE    DATE            NOT NULL,
    ARTIST_ID       INT             NOT NULL,

    FOREIGN KEY (ARTIST_ID) REFERENCES ARTIST(ARTIST_ID) ON DELETE CASCADE
);
CREATE TABLE TICKET (
    TICKET_ID       INT             AUTO_INCREMENT      PRIMARY KEY,
    CONCERT_ID      INT             NOT NULL,
    CUSTOMER_ID     INT             NOT NULL,
    SEAT_NUMBER     INT             NOT NULL,
    PRICE           DECIMAL(5, 2)   NOT NULL,

    FOREIGN KEY (CONCERT_ID)  REFERENCES CONCERT(CONCERT_ID)   ON DELETE CASCADE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE RESTRICT
);
-- bonus table
CREATE TABLE MERCHANDISE (
    MERCH_ID        INT             AUTO_INCREMENT      PRIMARY KEY,
    ARTIST_ID       INT             NOT NULL,
    CONCERT_ID      INT             NOT NULL,
    ITEM_NAME       VARCHAR(20)     NOT NULL,
    MERCH_PRICE     DECIMAL(5, 2)   NOT NULL,
    QUANTITY_SOLD   INT,

    FOREIGN KEY (CONCERT_ID)  REFERENCES CONCERT(CONCERT_ID)   ON DELETE CASCADE,
    FOREIGN KEY (ARTIST_ID)   REFERENCES ARTIST(ARTIST_ID)     ON DELETE CASCADE
);

-- Test Values
-- Artists
INSERT INTO ARTIST (ARTIST_NAME, GENRE) VALUES
('Lil Wayne', 'Rap'),
('Taylor Swift', 'Pop'),
('Metallica', 'Metal'),
('Beyonce', 'R&B');

-- Customers
INSERT INTO CUSTOMER (CUSTOMER_NAME) VALUES
('John Smith'),
('Jane Doe'),
('Bob Johnson'),
('Alice Brown');

-- Concerts (using ARTIST_IDs 1-4)
INSERT INTO CONCERT (VENUE_NAME, CITY, CONCERT_DATE, ARTIST_ID) VALUES
('Madison Square', 'New York', '2026-06-15', 1),
('Staples Center', 'Los Angeles', '2026-07-20', 2),
('Wembley Arena', 'London', '2026-08-10', 3),
('Toyota Center', 'Houston', '2026-09-05', 4);

-- Tickets
INSERT INTO TICKET (CONCERT_ID, CUSTOMER_ID, SEAT_NUMBER, PRICE) VALUES
(1, 1, 10, 49.99),
(1, 2, 11, 49.99),
(2, 3, 5, 99.99),
(3, 4, 22, 74.99),
(4, 1, 33, 59.99);

-- Merchandise
INSERT INTO MERCHANDISE (ARTIST_ID, CONCERT_ID, ITEM_NAME, MERCH_PRICE, QUANTITY_SOLD) VALUES
(1, 1, 'shirt', 23.99, 4),
(2, 2, 'cookbook', 49.99, 2),
(3, 3, 'poster', 14.99, 10),
(4, 4, 'hat', 29.99, 6);